#!/bin/bash
# Setup Supabase PostgreSQL Database (Free Tier)

set -e

echo "========================================"
echo "Setting up Supabase Database (Free Tier)"
echo "========================================"

echo ""
echo "Supabase offers 500MB PostgreSQL database for free!"
echo ""
echo "Manual Setup Steps:"
echo ""
echo "1. Create Account"
echo "   - Visit: https://supabase.com"
echo "   - Sign up with GitHub"
echo ""
echo "2. Create New Project"
echo "   - Click 'New Project'"
echo "   - Project name: image-captioning"
echo "   - Database password: (save this securely)"
echo "   - Region: Select closest to your users"
echo "   - Pricing plan: Free tier (500MB)"
echo ""
echo "3. Get Connection String"
echo "   - Go to Settings > Database"
echo "   - Copy 'Connection string' (URI format)"
echo "   - Replace [YOUR-PASSWORD] with your password"
echo ""
echo "4. Run Database Schema"
echo "   - Go to SQL Editor"
echo "   - Copy contents of backend/database/schema.sql"
echo "   - Click 'Run'"
echo ""
echo "5. Update Environment Variables"
echo ""
echo "   For Render (Backend):"
echo "     DATABASE_URL=postgresql://postgres:[password]@[host]:5432/postgres"
echo ""
echo "   For Local Development:"
echo "     Update backend/.env with the connection string"
echo ""
echo "Example connection string:"
echo "postgresql://postgres.abc123xyz.supabase.co:5432/postgres"
echo ""
echo "✅ Free Tier Limits:"
echo "   - 500MB database space"
echo "   - Up to 2GB bandwidth"
echo "   - Unlimited API requests"
echo "   - Automatic daily backups"
echo ""
echo "Need help? Visit: https://supabase.com/docs/guides/database"
